services:
  postgres:
    image: postgres:16
    container_name: film-postgres
    restart: always

    environment:
      POSTGRES_DB: films
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Redmi_1a

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - film-network

  backend:
    image: ghcr.io/kalio-sp/film-react-nest-backend:latest
    container_name: film-backend
    restart: always

    depends_on:
      - postgres

    environment:
      PORT: 3000

      DATABASE_DRIVER: postgres

      DATABASE_URL: postgres://postgres:Redmi_1a@postgres:5432/films

      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: films

      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Redmi_1a

    networks:
      - film-network

  frontend:
    image: ghcr.io/kalio-sp/film-react-nest-frontend:latest
    container_name: film-frontend

    volumes:
      - frontend_dist:/app/dist

    networks:
      - film-network

  nginx:
    image: ghcr.io/kalio-sp/film-react-nest-nginx:latest

    build:
      context: ./nginx

    container_name: film-nginx

    ports:
      - "80:80"

    depends_on:
      - backend
      - frontend

    volumes:
      - frontend_dist:/usr/share/nginx/html

    networks:
      - film-network

  pgadmin:
    image: dpage/pgadmin4

    container_name: film-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8080:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      - postgres

    networks:
      - film-network

volumes:
  postgres_data:
  pgadmin_data:
  frontend_dist:

networks:
  film-network:
    driver: bridge
